<?php
/**
 * Custom Drupal module for the ISSA Membership approval process
 *
 * @author Klaas Eikelboom (CiviCooP)
 * @date 19 Jan 2017
 * @license AGPL-3.0
 */


function issa_approval_menu()
{
    $items = array();
    $items['admin/config/system/issa-approval'] = array(
        'title' => 'Issa custom module',
        'description' => 'Configuration of the approval module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('_issa_approval_config_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['issa-approval/check-list'] = array(
        'title' => 'Check the approval steps',
        'description' => 'Configuration of the approval module',
        'page callback' => '_issa_approval_checklist',
        'page arguments' => array('_issa_approval_checklist'),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function _issa_approval_checklist()
{
    $items = array('Step 1','Step 2','Step 3');

    $output = array(
        'introduction' => array(
            '#type' => 'markup',
            '#markup' => '<p>The different steps in the approval process</p>'
        ),
        'steps' => array(
            array(
                '#items' => $items,
                '#theme' => 'item_list',
            ),
        )
    );
    return $output;
}


function _issa_approval_config_form($form, &$form_state)
{

    $query = db_query("SELECT nid, title FROM {node} WHERE type='webform'");
    $webformOptions = array();
    $records = $query->fetchAll();
    foreach ($records as $record) {
        $webformOptions[$record->nid] = $record->title;
    }


    civicrm_initialize();
    $result = civicrm_api3('RelationshipType','get',array());
    $relationshipTypeOptions = array();
    foreach($result['values'] as $value){
        if(isset($value['description'])) {
            $relationshipTypeOptions[$value['id']] = $value['description'];
        }
    }

    $form['issa_approval_webform_nid'] = array(
        "#title" => 'Select the webform, that must be used for the approval',
        '#type' => 'select',
        '#options' => $webformOptions,
        '#default_value' => variable_get('issa_approval_webform_nid', array_keys($webformOptions)[0]),
    );

    $form['issa_approval_employee_type_id'] = array(
        "#title" => 'Select the relationships that defines the collegues (maybe employee?)',
        '#type' => 'select',
        '#options' => $relationshipTypeOptions,
        '#default_value' => variable_get('issa_approval_employee_type_id', 5),
    );

    return system_settings_form($form);
}

/* colleagues block */
function issa_approval_block_info() {
    $blocks['issa_approval_colleagues'] = array(
        // info: The name of the block.
        'info' => t('Colleagues'),
    );
    return $blocks;
}

function issa_approval_block_view($delta = '')
{
    $block = array();
    switch ($delta) {
        case 'issa_approval_colleagues':
            $colleagues = issa_approval_helper::colleagues(issa_approval_helper::currentUser());
            $block['subject'] = t('Your organisation');
            $block['content'] = array(
                'colleagues' => array(
                    array(
                        '#items' => $colleagues,
                        '#theme' => 'item_list',
                    ),
                ));
            break;
    }
    return $block;
}

/* hook_views_api() */
function issa_approval_views_api()
{
    return [
        'api' => 3.0,
        'path' => drupal_get_path('module', 'issa_approval') . '/views',
    ];
}